version: '3.5'
services:
  mongo:
    image: mongo:4.2
    container_name: clav_mongo
    restart: always
    volumes:
      - mongodb-data:/data/db
  graphdb:
    image: ${GRAPHDB_IMG}
    container_name: clav_graphdb
    build:
      context: ./graphdb
      dockerfile: Dockerfile
      args:
        - version=${GRAPHDB_VERSION}
        - dataFile=${GRAPHDB_DATA_FILE}
    restart: always
    volumes:
      - graphdb-data:/opt/graphdb/home/data/repositories
  server:
    image: ${SERVER_IMG}
    container_name: clav_server
    build:
      context: ./CLAV2018
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
      - PROTOCOLS=https
      - DOMAINS=${DOMAINS}
      - GRAPHDB=graphdb:7200
      - MONGODB=mongo
      - API_VERSION=${API_VERSION}
      - INTERFACE_HOSTS=${INTERFACE_HOSTS}
      - SERVER_AUTH_HOST=http://clav-auth:7778
  clav-auth:
    image: ${SERVER_AUTH_IMG}
    container_name: clav_auth
    build:
      context: ./CLAV-auth
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
      - API_VERSION=${API_VERSION}
      - API_HOST=http://server:7779
  redis:
    image: redis:6.0
    container_name: clav_redis
    restart: always
    command: redis-server --requirepass redisPass123 --appendonly yes
    volumes:
      - acme-data:/data
  kong:
    image: kong:2.2.0-ubuntu
    container_name: clav_kong
    restart: always
    user: root
    ulimits:
      nofile:
        soft: 4096
        hard: 4096
    environment:
      - DOMAINS=${DOMAINS}
      - EMAIL=${EMAIL}
      - API_VERSION=${API_VERSION}
      - API_HOST=http://server:7779
      - SERVER_AUTH_HOST=http://clav-auth:7778
      - REDIS_HOST=redis
    ports:
      - ${HTTP_PORT}:8000
      - ${HTTPS_PORT}:8443
      # admin
      # 8001:8001
      # 8444:8444
    volumes:
      - ${PWD}/kong/kong.conf:/etc/kong/kong.conf
      - ${PWD}/kong/kong.yml.template:/usr/local/kong/declarative/kong.yml.template
      - ${PWD}/beforeStart.sh:/beforeStart.sh
      - ${PWD}/afterStart.sh:/afterStart.sh
      - ${PWD}/wait-for-it.sh:/wait-for-it.sh
    command: /bin/bash -c "/wait-for-it.sh clav-auth:7778 -- /wait-for-it.sh server:7779 -- /beforeStart.sh && su - kong && (kong start &) && sleep 10 && /afterStart.sh && tail -f /dev/null"
volumes:
  mongodb-data:
    external: false
    name: clav-mongodb-data
  graphdb-data:
    external: false
    name: clav-graphdb-data
  acme-data:
    external: false
    name: clav-acme-data
